# Generated by Django 3.1.6 on 2021-12-10 06:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(1, 'Serie must be greater than 1 characters')])),
                ('episode', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(1, 'episode must be greater than 1 characters')])),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('episode', 'user')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_episodes', through='searchengine.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
